name: Daily compatibility check against latest polkadot

on:
  workflow_dispatch:
    inputs:
      gitlab_pipeline:
        description: 'Link to failed pipeline'
        required: true

jobs:
  create-an-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout staking-miner sources
        uses: actions/checkout@v3

      - name: Create an issue
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLAB_PIPELINE_URL: ${{ inputs.gitlab_pipeline }}
        with:
          # Use this issue template:
          filename: .github/issue_templates/nightly_run_failed.md
          # Update existing issue if found; hopefully will make it clearer
          # that it is still an issue:
          update_existing: true
          # Look for new *open* issues in this search (we want to
          # create a new one if we only find closed versions):
          search_existing: open
